In [1]:
import numpy as np

In [2]:
list = [0,1,2,3,4,5,6,7,8]

matrix = np.array(list).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
axis1a = np.array([matrix[0,0],matrix[1,0],matrix[2,0]])
axis1b = np.array([matrix[0,1],matrix[1,1],matrix[2,1]])
axis1c = np.array([matrix[0,2],matrix[1,2],matrix[2,2]])

axis1 = [axis1a, axis1b, axis1c]
axis1

[array([0, 3, 6]), array([1, 4, 7]), array([2, 5, 8])]

In [4]:
axis2a = np.array([matrix[0,0],matrix[0,1],matrix[0,2]])
axis2b = np.array([matrix[1,0],matrix[1,1],matrix[1,2]])
axis2c = np.array([matrix[2,0],matrix[2,1],matrix[2,2]])

axis2 = [axis2a, axis2b, axis2c]
axis2

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [5]:
mean1a = axis1a.mean()
mean1b = axis1b.mean()
mean1c = axis1c.mean()

mean_a1 = [mean1a, mean1b, mean1c]
mean_a1

[3.0, 4.0, 5.0]

In [6]:
mean2a = axis2a.mean()
mean2b = axis2b.mean()
mean2c = axis2c.mean()

mean_a2 = [mean2a, mean2b, mean2c]
mean_a2

[1.0, 4.0, 7.0]

In [7]:
mean_flat = matrix.mean()

mean_flat

4.0

In [8]:
var1a = axis1a.var()
var1b = axis1b.var()
var1c = axis1c.var()

var_a1 = [var1a, var1b, var1c]
var_a1

[6.0, 6.0, 6.0]

In [9]:
var2a = axis2a.var()
var2b = axis2b.var()
var2c = axis2c.var()

var_a2 = [var2a, var2b, var2c]
var_a2

[0.6666666666666666, 0.6666666666666666, 0.6666666666666666]

In [10]:
var_flat = matrix.var()

var_flat

6.666666666666667

In [11]:
std1a = axis1a.std()
std1b = axis1b.std()
std1c = axis1c.std()

std_a1 = [std1a, std1b, std1c]
std_a1

[2.449489742783178, 2.449489742783178, 2.449489742783178]

In [12]:
std2a = axis2a.std()
std2b = axis2b.std()
std2c = axis2c.std()

std_a2 = [std2a, std2b, std2c]
std_a2

[0.816496580927726, 0.816496580927726, 0.816496580927726]

In [13]:
std_flat = matrix.std()

std_flat

2.581988897471611

In [14]:
max1a = axis1a.max()
max1b = axis1b.max()
max1c = axis1c.max()

max_a1 = [max1a, max1b, max1c]
max_a1

[6, 7, 8]

In [15]:
max2a = axis2a.max()
max2b = axis2b.max()
max2c = axis2c.max()

max_a2 = [max2a, max2b, max2c]
max_a2

[2, 5, 8]

In [16]:
max_flat = matrix.max()

max_flat

8

In [17]:
min1a = axis1a.min()
min1b = axis1b.min()
min1c = axis1c.min()

min_a1 = [min1a, min1b, min1c]
min_a1

[0, 1, 2]

In [18]:
min2a = axis2a.min()
min2b = axis2b.min()
min2c = axis2c.min()

min_a2 = [min2a, min2b, min2c]
min_a2

[0, 3, 6]

In [19]:
min_flat = matrix.min()
min_flat

0

In [20]:
sum1a = axis1a.sum()
sum1b = axis1b.sum()
sum1c = axis1c.sum()

sum_a1 = [sum1a, sum1b, sum1c]
sum_a1

[9, 12, 15]

In [21]:
sum2a = axis2a.sum()
sum2b = axis2b.sum()
sum2c = axis2c.sum()

sum_a2 = [sum2a, sum2b, sum2c]
sum_a2

[3, 12, 21]

In [22]:
sum_flat = matrix.sum()
sum_flat

36

In [23]:
data_dict = {
             'mean':[mean_a1, mean_a2, mean_flat],
             'variance':[var_a1, var_a2, var_flat],
             'standard deviation':[std_a1, std_a2, std_flat],
             'max':[max_a1, max_a2, max_flat],
             'min':[min_a1, min_a2, min_flat],
             'sum':[sum_a1, sum_a2, sum_flat]
            }
data_dict

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}